# 01. Data Cleaning & Preparation

Clean the four source tables, parse the text timestamp, validate relationships, and export analysis-ready CSVs.

In [ ]:

# ========== 1. Environment ==========
!pip install -q pandas numpy matplotlib sqlalchemy pymysql openpyxl

In [15]:

# ========== 2. MySQL Connection ==========
from pathlib import Path
import warnings
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 100)

DB_URL = "mysql+pymysql://root:wu200203@localhost:3306/project2"
engine = create_engine(DB_URL)

DATA_DIR = Path("../data/processed")
DATA_DIR.mkdir(parents=True, exist_ok=True)

print("Connection object created.")
# Test connection:
with engine.connect() as conn:
    print(conn.execute(text("SELECT 1")).scalar())

Connection object created.
1

In [16]:

# ========== 3. Load Raw Tables ==========
campaigns = pd.read_sql("SELECT * FROM campaigns", engine)
ads = pd.read_sql("SELECT * FROM ads", engine)
users = pd.read_sql("SELECT * FROM users", engine)
ad_events = pd.read_sql("SELECT * FROM ad_events", engine)

for name, df in {
    "campaigns": campaigns,
    "ads": ads,
    "users": users,
    "ad_events": ad_events
}.items():
    print(f"{name}: {df.shape}")
    display(df.head(3))

campaigns: (50, 6)

,campaign_id,name,start_date,end_date,duration_days,total_budget
0,1,Campaign_1_Launch,25/05/2025,23/07/2025,59,24021.32
1,2,Campaign_2_Launch,16/04/2025,07/07/2025,82,79342.41
2,3,Campaign_3_Winter,04/05/2025,29/06/2025,56,14343.25

ads: (200, 7)

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,target_interests
0,1,28,Facebook,Video,Female,35-44,"art, technology"
1,2,33,Facebook,Stories,All,25-34,"travel, photography"
2,3,20,Instagram,Carousel,All,25-34,technology

users: (1246, 7)

,user_id,user_gender,user_age,age_group,country,location,interests
0,12.0,Male,56,55-65,Japan,New Jeremy,"lifestyle, health"
1,50.0,Female,17,16-17,Canada,Lake Juanville,"food, finance"
2,62.0,Female,16,16-17,France,Davidside,"photography, art, food"

ad_events: (119711, 7)

,event_id,ad_id,user_id,timestamp,day_of_week,time_of_day,event_type
0,1,197,2359b,26/07/2025 0:19,Saturday,Night,Like
1,2,51,f9c67,15/06/2025 8:28,Sunday,Morning,Share
2,3,46,5b868,27/06/2025 0:40,Friday,Night,Impression

In [17]:

# ========== 4. Basic Structure & Missing Values ==========
for name, df in {
    "campaigns": campaigns,
    "ads": ads,
    "users": users,
    "ad_events": ad_events
}.items():
    print("\n" + "="*70)
    print(name)
    print(df.dtypes)
    print("\nMissing values:")
    display(df.isna().sum().sort_values(ascending=False).head(20))
    print("\nDuplicated rows:", df.duplicated().sum())

======================================================================
campaigns
campaign_id        int64
name              object
start_date        object
end_date          object
duration_days      int64
total_budget     float64
dtype: object

Missing values:

campaign_id      0
name             0
start_date       0
end_date         0
duration_days    0
total_budget     0
dtype: int64

Duplicated rows: 0

======================================================================
ads
ad_id                int64
campaign_id          int64
ad_platform         object
ad_type             object
target_gender       object
target_age_group    object
target_interests    object
dtype: object

Missing values:

ad_id               0
campaign_id         0
ad_platform         0
ad_type             0
target_gender       0
target_age_group    0
target_interests    0
dtype: int64

Duplicated rows: 0

======================================================================
users
user_id        float64
user_gender     object
user_age         int64
age_group       object
country         object
location        object
interests       object
dtype: object

Missing values:

user_id        0
user_gender    0
user_age       0
age_group      0
country        0
location       0
interests      0
dtype: int64

Duplicated rows: 0

======================================================================
ad_events
event_id        int64
ad_id           int64
user_id        object
timestamp      object
day_of_week    object
time_of_day    object
event_type     object
dtype: object

Missing values:

event_id       0
ad_id          0
user_id        0
timestamp      0
day_of_week    0
time_of_day    0
event_type     0
dtype: int64

Duplicated rows: 0

In [18]:

# ========== 5. Standardize Column Names ==========
def normalize_columns(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )
    return df

campaigns = normalize_columns(campaigns)
ads = normalize_columns(ads)
users = normalize_columns(users)
ad_events = normalize_columns(ad_events)

print("campaigns:", campaigns.columns.tolist())
print("ads:", ads.columns.tolist())
print("users:", users.columns.tolist())
print("ad_events:", ad_events.columns.tolist())

campaigns: ['campaign_id', 'name', 'start_date', 'end_date', 'duration_days', 'total_budget']
ads: ['ad_id', 'campaign_id', 'ad_platform', 'ad_type', 'target_gender', 'target_age_group', 'target_interests']
users: ['user_id', 'user_gender', 'user_age', 'age_group', 'country', 'location', 'interests']
ad_events: ['event_id', 'ad_id', 'user_id', 'timestamp', 'day_of_week', 'time_of_day', 'event_type']

In [19]:

# ========== 5B. Standardize ID Columns ==========
# Keep identifiers as strings so joins work even when CSV type inference differs.
id_map = {
    "campaigns": ["campaign_id"],
    "ads": ["ad_id", "campaign_id"],
    "users": ["user_id"],
    "ad_events": ["event_id", "ad_id", "user_id"]
}

dataframes = {
    "campaigns": campaigns,
    "ads": ads,
    "users": users,
    "ad_events": ad_events
}

for df_name, cols in id_map.items():
    df = dataframes[df_name]
    for col in cols:
        if col in df.columns:
            df[col] = df[col].astype("string").str.strip()
            df[col] = df[col].replace({
                "nan": pd.NA,
                "None": pd.NA,
                "": pd.NA
            })

In [20]:

# ========== 6. Clean Key String Columns ==========
for df in [campaigns, ads, users, ad_events]:
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].astype("string").str.strip()

# Standardize event_type values
if "event_type" in ad_events.columns:
    ad_events["event_type"] = ad_events["event_type"].str.title()

# Standardize ad_type/platform when present
for df, cols in [
    (ads, ["ad_type"]),
    (campaigns, ["platform"])
]:
    for col in cols:
        if col in df.columns:
            df[col] = df[col].str.title()

In [21]:

# ========== 6B. Clean Numeric Columns ==========
for df in [campaigns, ads, users, ad_events]:
    for col in ["age", "total_budget", "budget", "actual_spend", "spend", "revenue", "purchase_value"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

In [22]:

# ========== 7. Parse TEXT timestamp ==========
# Your source format is like: 26/07/2025 01:19
if "timestamp" not in ad_events.columns:
    raise KeyError("Expected ad_events column `timestamp` was not found.")

raw_ts = ad_events["timestamp"].astype("string").str.strip()

# Primary parse using day-first. This handles both 01:19 and 8:28.
ad_events["event_datetime"] = pd.to_datetime(
    raw_ts,
    dayfirst=True,
    errors="coerce"
)

# Fallback for any values that did not parse
mask = ad_events["event_datetime"].isna()
if mask.any():
    ad_events.loc[mask, "event_datetime"] = pd.to_datetime(
        raw_ts[mask],
        format="%d/%m/%Y %H:%M",
        errors="coerce"
    )

print("Unparsed timestamps:", ad_events["event_datetime"].isna().sum())
print("Date range:", ad_events["event_datetime"].min(), "to", ad_events["event_datetime"].max())

display(
    ad_events[["timestamp", "event_datetime"]]
    .head(10)
)

Unparsed timestamps: 0
Date range: 2025-05-07 14:12:00 to 2025-08-06 14:11:00

          timestamp      event_datetime
0   26/07/2025 0:19 2025-07-26 00:19:00
1   15/06/2025 8:28 2025-06-15 08:28:00
2   27/06/2025 0:40 2025-06-27 00:40:00
3  05/06/2025 19:20 2025-06-05 19:20:00
4   22/07/2025 8:30 2025-07-22 08:30:00
5  30/06/2025 15:19 2025-06-30 15:19:00
6  22/06/2025 14:24 2025-06-22 14:24:00
7   10/07/2025 1:50 2025-07-10 01:50:00
8  26/06/2025 19:31 2025-06-26 19:31:00
9   29/06/2025 5:45 2025-06-29 05:45:00

In [23]:

# ========== 8. Rebuild Time Dimensions from event_datetime ==========
ad_events["event_date"] = pd.to_datetime(ad_events["event_datetime"].dt.date)

ad_events["year"] = ad_events["event_datetime"].dt.year
ad_events["month"] = ad_events["event_datetime"].dt.to_period("M").astype(str)
ad_events["week"] = ad_events["event_datetime"].dt.to_period("W").astype(str)

ad_events["day_of_week"] = ad_events["event_datetime"].dt.day_name()
ad_events["day_of_week_num"] = ad_events["event_datetime"].dt.dayofweek

# Simple, unique time-of-day buckets:
# 00:00-05:59 Night
# 06:00-11:59 Morning
# 12:00-17:59 Afternoon
# 18:00-23:59 Evening
hour = ad_events["event_datetime"].dt.hour
ad_events["time_of_day"] = pd.cut(
    hour,
    bins=[-1, 6, 12, 18, 24],
    labels=["Night", "Morning", "Afternoon", "Evening"],
    include_lowest=True,
    right=False
)

dow_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
ad_events["day_of_week"] = pd.Categorical(
    ad_events["day_of_week"],
    categories=dow_order,
    ordered=True
)

In [24]:

# ========== 9. Remove Exact Duplicates & Invalid Rows ==========
for df_name, df in [
    ("campaigns", campaigns),
    ("ads", ads),
    ("users", users),
    ("ad_events", ad_events)
]:
    before = len(df)
    df.drop_duplicates(inplace=True)
    print(f"{df_name}: removed {before - len(df)} duplicate rows")

# Keep only rows with critical event fields
critical = ["event_id", "ad_id", "user_id", "event_datetime", "event_type"]
existing_critical = [c for c in critical if c in ad_events.columns]
ad_events = ad_events.dropna(subset=existing_critical).copy()

valid_events = {"Impression", "Click", "Like", "Share", "Comment", "Purchase"}
if "event_type" in ad_events.columns:
    ad_events = ad_events[ad_events["event_type"].isin(valid_events)].copy()

print("Cleaned ad_events rows:", len(ad_events))

campaigns: removed 0 duplicate rows
ads: removed 0 duplicate rows
users: removed 0 duplicate rows
ad_events: removed 0 duplicate rows
Cleaned ad_events rows: 119711

In [25]:

# ========== 10. Relationship Checks ==========
def check_key_relationship(child, child_key, parent, parent_key, name):
    if child_key not in child.columns or parent_key not in parent.columns:
        print(f"{name}: skipped because key column is missing.")
        return
    unmatched = ~child[child_key].isin(parent[parent_key].dropna().unique())
    print(f"{name}: unmatched rows = {unmatched.sum():,}")

check_key_relationship(ads, "campaign_id", campaigns, "campaign_id", "ads -> campaigns")
check_key_relationship(ad_events, "ad_id", ads, "ad_id", "ad_events -> ads")
check_key_relationship(ad_events, "user_id", users, "user_id", "ad_events -> users")

ads -> campaigns: unmatched rows = 0
ad_events -> ads: unmatched rows = 0
ad_events -> users: unmatched rows = 119,711

In [26]:

# ========== 11. Save Processed Data ==========
campaigns.to_csv(DATA_DIR / "campaigns_clean.csv", index=False)
ads.to_csv(DATA_DIR / "ads_clean.csv", index=False)
users.to_csv(DATA_DIR / "users_clean.csv", index=False)
ad_events.to_csv(DATA_DIR / "ad_events_clean.csv", index=False)

print("Saved to:", DATA_DIR.resolve())

Saved to: /Users/wuchaoqun/Desktop/Project2/data/processed

In [27]:

# ========== 12. Final Data Quality Summary ==========
quality_summary = pd.DataFrame({
    "table": ["campaigns", "ads", "users", "ad_events"],
    "rows": [len(campaigns), len(ads), len(users), len(ad_events)],
    "columns": [campaigns.shape[1], ads.shape[1], users.shape[1], ad_events.shape[1]],
    "missing_cells": [
        int(campaigns.isna().sum().sum()),
        int(ads.isna().sum().sum()),
        int(users.isna().sum().sum()),
        int(ad_events.isna().sum().sum())
    ]
})
display(quality_summary)

       table    rows  columns  missing_cells
0  campaigns      50        6              0
1        ads     200        7              0
2      users    1246        7              0
3  ad_events  119711       13              0